CURRENT_INVENTORY = {
    "mushroom": "many",
    "sour_cream": "normal",
    "butter": "normal",
    "eggs": "many",
    "chicken_fillet": "normal",
    "rice": "little",
    "buckwheat": "normal",
    "corn_grits": "normal",
    "semolina": "normal",
    "milk": "little",
    "zeltz": "little",
    "boiled_sausage": "normal",
    "young_cabbage": "normal",
    "greens": "little",
    "pelmeni": "normal",
    "vareniki": "normal",
    "smalec": "normal",
    "stew": "little",
    "canned_peas": "many",
    "hard_cheese": "normal",
    "onion": "normal",
    "potato": "normal",
    "carrot": "little",
    "red_lentils": "little",
    "dry_garlic": "spice",
    "black_pepper": "spice",
    "flour": "little",
    }
    
